services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\KimaiMobileGPSInfoBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'
